"""empty message

Revision ID: 84278acf8c22
Revises: ded2ad20142f
Create Date: 2025-03-21 12:47:34.685704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84278acf8c22'
down_revision = 'ded2ad20142f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
